basics:
    startwith: 10
    gainlives: true #default true.  When false, players can only lose lives.
#    
#  The following features/options are placeholders.  These are not yet implimented    
#
    jailondeath: false #default false.  When true, players are Jailed instead of banned.
    resetbansafter: 0 #time days that bans are reset.  
db:
  mysql:
    enable: false
    user: "root"
    pass: "password"
    host: "localhost"
    port: 3306
    db: "minecraft"
#Databases are not yet enabled.